build:
	mvn clean package

run-pipe-stream:
	mvn exec:java -Dexec.mainClass=myapps.Pipe

run-line-split-stream:
	mvn exec:java -Dexec.mainClass=myapps.LineSplit

run-word-count-stream:
	mvn exec:java -Dexec.mainClass=myapps.WordCount
